# Generated by Django 5.0.1 on 2026-05-12 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('baseline', 'Baseline'), ('linear', 'Regresión Lineal'), ('decision_tree', 'Decision Tree'), ('random_forest', 'Random Forest'), ('extra_trees', 'Extra Trees'), ('gradient_boosting', 'Gradient Boosting'), ('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('stacking', 'Stacking')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('rmse', models.FloatField(blank=True, help_text='Root Mean Squared Error', null=True)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error', null=True)),
                ('r2_score', models.FloatField(blank=True, help_text='R² Score', null=True)),
                ('mape', models.FloatField(blank=True, help_text='Mean Absolute Percentage Error', null=True)),
                ('medae', models.FloatField(blank=True, help_text='Median Absolute Error', null=True)),
                ('me', models.FloatField(blank=True, help_text='Mean Error (Bias)', null=True)),
                ('mpe', models.FloatField(blank=True, help_text='Mean Percentage Error', null=True)),
                ('r2_std', models.FloatField(blank=True, null=True)),
                ('rmse_std', models.FloatField(blank=True, null=True)),
                ('mae_std', models.FloatField(blank=True, null=True)),
                ('train_r2', models.FloatField(blank=True, null=True)),
                ('train_rmse', models.FloatField(blank=True, null=True)),
                ('train_mae', models.FloatField(blank=True, null=True)),
                ('overfitting_gap', models.FloatField(blank=True, help_text='Diferencia entre R² train y test', null=True)),
                ('training_time', models.FloatField(blank=True, help_text='Tiempo de entrenamiento en segundos', null=True)),
                ('n_samples', models.IntegerField(blank=True, help_text='Número de muestras de entrenamiento', null=True)),
                ('n_features', models.IntegerField(blank=True, help_text='Número de features', null=True)),
                ('hyperparameters', models.JSONField(blank=True, null=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=100, unique=True)),
                ('area_code', models.CharField(blank=True, max_length=10)),
                ('year', models.IntegerField(default=2025)),
                ('woz_value', models.IntegerField(help_text='Official WOZ assessed value in €')),
                ('housing_stock', models.IntegerField(help_text='Total number of dwellings')),
                ('housing_density', models.IntegerField(help_text='Dwellings per km²')),
                ('population', models.IntegerField(help_text='Total population')),
                ('avg_area_m2', models.FloatField(help_text='Average dwelling size in m²')),
                ('area_0_40', models.IntegerField(default=0)),
                ('area_40_60', models.IntegerField(default=0)),
                ('area_60_80', models.IntegerField(default=0)),
                ('area_80_100', models.IntegerField(default=0)),
                ('area_100_plus', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Neighborhood Stats',
                'verbose_name_plural': 'Neighborhood Stats',
                'ordering': ['-woz_value'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('studio', 'Estudio'), ('room', 'Habitación')], default='apartment', max_length=50)),
                ('url', models.URLField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de venta en euros', max_digits=10)),
                ('predicted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address', models.CharField(max_length=500)),
                ('neighborhood', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(default='Amsterdam', max_length=100)),
                ('zip_code', models.CharField(blank=True, help_text='Código postal', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('living_area', models.FloatField(blank=True, help_text='m²', null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, help_text='Número de baños', null=True)),
                ('year_built', models.IntegerField(blank=True, help_text='Año de construcción', null=True)),
                ('floor', models.IntegerField(blank=True, help_text='Número de piso', null=True)),
                ('energy_label', models.CharField(blank=True, help_text='Certificado energético (A, B, C, etc.)', max_length=10)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('listed_since', models.CharField(blank=True, help_text='Fecha desde que está en el mercado', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['neighborhood'], name='idx_neighborhood'), models.Index(fields=['property_type'], name='idx_property_type'), models.Index(fields=['price'], name='idx_price'), models.Index(fields=['living_area'], name='idx_living_area'), models.Index(fields=['predicted_price'], name='idx_predicted_price'), models.Index(fields=['is_active'], name='idx_is_active'), models.Index(fields=['zip_code'], name='idx_zip_code'), models.Index(fields=['is_active', 'predicted_price'], name='idx_active_predicted'), models.Index(fields=['neighborhood', 'price'], name='idx_neigh_price')],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.mlmodel')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='properties.property')),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
